c4deszes/ldfparser

.github/workflows/build.yml, README.md, examples/create_frame.py, examples/network.ldf, examples/signal_encoding.py, ldfparser/encoding.py, ldfparser/ldf.lark, ldfparser/lin.py, ldfparser/parser.py, pytest.ini, setup.py, tests/test_data_encoding.py, tests/test_frame.py, tests/test_parser.py, tests/test_signal_encoding.py
LDF parser will now load signal encoding types and representations
Signals can now be passed using the human friendly values
Added example showcasing signal encoding
Updated LDF Lark syntax to support encoding types and representations
Added encoding and decoding classes PhysicalValue and LogicalValue
LinFrame now raises Exception when Signals overlap or are out of frame
More tests have been added
=> Adding ability to encode and decode Signal values

README.md, examples/network.ldf, examples/read_header.py, ldfparser/ldf.lark, ldfparser/parser.py, tests/test_parser.py
Updated LDF Lark
LDFParser has protocol_version, language_version and baudrate properties
Added tests for header parsing
Added example of header parsing
Updated Readme with header usage example
=> Adds support for getting header information

ldfparser/ldf.lark, setup.py
Added support for negative values of floating point fields
Bumped version number to 0.3.1
=> Fixing error when physical value scale is negative

.github/workflows/build.yml, README.md
CI workflow now generates coverage report and uploads to codecov.io
Added codecov badge to README
=> Added code coverage metric

.github/workflows/build.yml, setup.cfg, setup.py
Added Matrix option of Python version
Switched to official Python docker image
Coverage now only published for version 3.8
=> Updated CI workflow

ldfparser/ldf.lark
=> Fix AssignFrameIdRange

ldfparser/parser.py
* Some LDF files requires specifying the encoding manually
=> Allow specifying the encoding when reading files

.flake8, .github/workflows/lint.yml
=> Added workflow for linting

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE/pull_request_template.md, CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md
Added Python versions and License badge
Added contributors section to README
Added PR template
Updated Bug report and Feature request issue templates
=> Added contributing guide and code of conduct

.github/workflows/build.yml
Pushes to development branch will release artifacts to Test PyPI
Commits tagged with version number will be released to PyPI
Pull requests will no longer trigger release
=> Changed the release workflow

.github/workflows/build.yml, .gitignore, pytest.ini, tests/snapshot_data.py, tests/test_comment.py, tests/test_json.py, tests/test_signal.py
Added script that generates snapshot data
Added workflow that executes snapshot tests against target branch
Added new marker to pytest 'snapshot'
Added test for comparing JSON output of the LDF parser to snapshot
=> Snapshot testing

.github/workflows/build.yml, ldfparser/ldf.lark, ldfparser/parser.py, tests/ldf/lin21.ldf, tests/ldf/lin22.ldf
AssignFrameIdRange command now only accepts 0 or 4 PID values
Adds parameters to conditional change nad command
Adds parameters to assign frame id range command
Adds parameters to assign frame id command
Parsing tests are updated with examples of these commands
=> Schedule table command parsing into dictionary

.github/workflows/build.yml, .github/workflows/lint.yml, .gitignore, README.md, docs/CLI.md, ldfparser/cli.py, ldfparser/lin.py, ldfparser/node.py, ldfparser/parser.py, setup.py, tests/test_cli.py
Basic CLI functionality is now present
Adds CLI entrypoint to setup.py
Adds CLI documentation
LDF container now contains the source dictionary
Fixes signals incorrectly being appended to the published frame list
Implements feature request #32 
Parser has not been modified, only a patch to the LDF containers content.
CLI functionality is tested both manually and via pytest, only command execution is verified and not whether the returned content is correct.
=> Adds a CLI interface for basic LDF tasks

.github/workflows/build.yml, .github/workflows/lint.yml, .gitignore, README.md, docs/CLI.md, ldfparser/cli.py, ldfparser/lin.py, ldfparser/node.py, ldfparser/parser.py, setup.cfg, setup.py, tests/test_cli.py
Merges #33 into master
Version number bumped to 0.7.0
=> Merge CLI functionality into master

.github/workflows/build.yml, README.md, requirements.txt
Development dependencies (pytest, flake8, etc.) have been moved into the requirements.txt file
Added badge and link to GH Pages
=> Adds link to Github Pages

docs/index.md, setup.py
+ Fixes license link in documentation
+ Replaces documentation link in setup.py with Github pages link
=> Fixes links in the documentation and setup.py

docs/frames.md, docs/index.md, docs/signals.md
Frames and signals are documented on the Github pages.
=> Adds frame and signal documentation

CHANGELOG.md, setup.cfg
Bumped version to 0.8.0 and updated the changelog.
=> Bumps version to 0.8.0

.github/workflows/release.yml
+ Release workflow doesn't work as expected, will be tried in a different repository later
=> Disables automatic changelog and asset upload

.github/pull_request_template.md, CHANGELOG.md
The PR template now contains a checklist to update the changelog and verify test results, it also fixes changelog entry of 0.9.0 release.
=> Adds checklist to PR template

CHANGELOG.md, ldfparser/node.py, ldfparser/parser.py, setup.cfg, tests/test_parser.py
Configurable frames, Response Error and Fault State Signals are now populated.
+ #65 
+ Tests have been added to see whether signals and frames are correctly linked
=> Fixes certain attributes not being parsed

setup.cfg
+ Version number not being updated
=> Bumps version number to 0.10.0

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, README.md, docs/frames.md, docs/parser.md, docs/signals.md
+ This should allow opening this repository inside a more consistent environment as well as Github Codespaces.
=> Adds devcontainer configuration

.github/workflows/build.yml
Codecov action v1 is being shutdown, see https://about.codecov.io/blog/introducing-codecovs-new-uploader/
=> Codecov action update

.github/ISSUE_TEMPLATE/bug_report.md, .github/pull_request_template.md
- An update to the Pull Request and Bug report template.
- Bug report template now contains instructions to provide dependency information, this
will be useful because we don't pin dependencies to exact versions.
- PR template is now more concise and the checklist has been extended further to make sure it's complete
=> Updates PR and bug report template

.gitattributes, README.md, docs/external/LIN_1.3.pdf, docs/external/LIN_2.0.pdf, docs/external/LIN_2.1.pdf, docs/external/LIN_2.2A.pdf
- LIN standards have been added as external documentation just so it's clear what documents are used as inputs.
=> Adds LIN standard documentations

CHANGELOG.md, ldfparser/frame.py, ldfparser/ldf.py, ldfparser/parser.py, ldfparser/templates/ldf.jinja2, schemas/ldf.json, tests/ldf/ldf_with_sporadic_frames.ldf, tests/test_parser.py
- Sporadic frames are now loaded and the contained unconditional frames are resolved.
+ Resolves #103 
+ `LDF::get_frame` signature has changed, but the return typehint shouldn't affect anyone
=> Sporadic frame support

docs/external/LIN_1.3.pdf, docs/external/LIN_2.0.pdf, docs/external/LIN_2.1.pdf, docs/external/LIN_2.2A.pdf
- Due to misuse files stored under LFS are deleted
- Entire year's LFS bandwidth was consumed
+ Describe the bug or feature and link to relevant issues
+ Analyze how the change might impact existing code
+ Provide evidence that the feature is tested and covered properly
=> Repository misuse LFS bandwidth consumed
