ldfparser/lin.py
setup.py
tests/test_frame.py

In the LIN specification Signals are effectively rotated twice when encoding and decoding. This pull request corrects #5 with an additional step to flip bytes before packing.

Correction of #5

---

ldfparser/ldf.lark
tests/ldf/valid.ldf

Fixed only one slave being allowed in the "Slaves" field of the LDF
Added extra fields for timebase and jitter in the "Master" field of LDF
Updated valid.ldf file to include multiple slaves
Fixes issue [uCAN-LIN/LinUSBConverter#5](https://github.com/uCAN-LIN/LinUSBConverter/issues/5)

Adds support for multiple slaves in LDF

---

ldfparser/comment.lark
ldfparser/ldf.lark
requirements.txt
setup.py

* Use recommended comment regex by lark. See https://github.com/lark-parser/lark/blob/master/lark/grammars/common.lark#L58
There are edge cases where the existing regex fail, and the one recommended by lark pass

Use recommended comment regex by lark

---

ldfparser/ldf.lark
tests/ldf/no_signal_subscribers.ldf
tests/test_parser.py

Due to confidentiality I can't share the full LDF file, I only kept enough of it to reproduce the problem.

Allow signal with no subscribers and empty node attribute section

---

ldfparser/lin.py
setup.cfg
tests/test_frame.py

The logic for frame encoding now uses `in` instead of the `get` operator when checking whether a signal is specified in the data.
This issue was discovered by an external user.
+ Frame encoding zero valued signals incorrectly uses the initial value.
+ Previous coverage values were misleading, there were no tests for the "signal fallback" mechanism but the branches were covered because most of the tests used 0 as the initial value.
+ Added more tests to cover this scenario.

Fixes zero signal encoding behavior

---

CHANGELOG.md
requirements.txt
schemas/ldf.json
tests/test_schema.py

Currently the parsing mechanism transforms the LDF into a dictionary (JSON) however the format of this dictionary is not locked, so users cannot rely on a stable schema. The format is somewhat locked, we have snapshot tests for the outputs so we know if a PR breaks the format but the schema itself may not be evident to developers using the dictionary feature or to other tools interfacing with the output.
+ Functionality will be unit tested using `jsonschema` library

Adds JSON schema for LDF tree

---

ldfparser/ldf.lark
schemas/ldf.json
tests/ldf/lin_encoders.ldf
tests/test_parser.py

LIN 2.1 allows for BCD and ASCII encodings to be specified. Seems like the types were defined but not included in `signal_encoding_type`.
* adds the relevant types to `signal_encoding_type` definition.
The LIN spec document doesn't include BCD or ASCII examples in the relevant sections (9.2.6.1 or 9.4.1) so I've added a few to [an LDF with all the existing examples](https://github.com/c4deszes/ldfparser/files/6650197/test_ldf.txt) (extension is .txt because of GitHub extension filter). This change doesn't interfere with any of the LDF testing files.
Since the types are already defined in the lark file & python code this seems like a simple oversight.

Fixes missing encoding types `ascii_value` and `bcd_value`.

---

.gitattributes
CHANGELOG.md
ldfparser/parser.py
tests/test_parser.py

The LIN signal dictionary is being appended to the subscribed to list of `LinSlave`, instead of a `LinSignal` object.
Fixes #58 
+ *Test case pending*

Fixes subscribed_to attribute on LinSlave objects

---

CHANGELOG.md
ldfparser/ldf.lark
tests/ldf/lin13.ldf

Whitespaces are not allowed in the Nodes section of the LDF in the Master and Slave definitions before the colon.
The following is not allowed `Master : CEM, 5 ms, 0.1 ms;` while `Master: CEM, 5 ms, 0.1 ms;` does work.
The `:` token has been separated from the keyword tokens. No other cases of merged tokens was noticed. 
Fixes #60 
The version 1.3 LDF has been updated to contain whitespace in the node definition section.

Syntax now allows whitespace in master definition

---

ldfparser/ldf.lark
ldfparser/parser.py
schemas/ldf.json
tests/ldf/lin_encoders.ldf
tests/test_parser.py

The current lark file and parser doesn't read the correct initial value of an array type signal. The JSON schema part for array signal init values is also missing.
This is reopening/reworking #57 but without fixing issues in the encoding and other parts.
Init values should be read correctly, including hexadecimal values
Encoding test has been extended to check the initial value of the array signals.

Fixes parsing initial values of array signals

---

CHANGELOG.md
ldfparser/lark/ldf.lark
setup.cfg

The parser currently expects floating numbers in `[0-9]+(\.[0-9]+)?` format, scientific notation however allows the usage of exponentials (e.g.: `1.2345e-05`).
The LIN standard doesn't mention scientific notation and for the real number definition it specifies that it's a number with a decimal point. The addition of this shouldn't cause any problems.
+ Resolves #74
+ The scientific notation's "e" suffix is optional, LDFs only using standard notation will work the same as before.

Allows scientific notation to be used

---

CHANGELOG.md
README.md
docs/index.md
docs/schedules.md
ldfparser/diagnostics.py
ldfparser/frame.py
ldfparser/ldf.py
ldfparser/parser.py
ldfparser/schedule.py
schemas/ldf.json
setup.cfg
tests/ldf/lin_schedules.ldf
tests/test_schedule.py

+ Schedule tables are parsed into the intermediate dictionary but they're not converted into Python objects afterwards
+ This information could be used by a LIN master device or a network simulator to perform the requested schedule
+ The way these master APIs work shall be taken into account
+ Resolves #79
+ Feature is completely new therefore no breaking changes are expected

Adds schedule table support

---

docs/schedules.md

- Function name in the documentation showing how to use schedule table information is wrong
+ Fixes #86

Fixes function name in schedule table example

---

CHANGELOG.md
ldfparser/parser.py
setup.cfg

- The `P2_min`, `ST_min` and `N_As`, `N_Cr` timeouts are set incorrectly when the values are not provided in the LDF,
this is because the parser uses `None` as the default, but the `LinSlave` class had the correct defaults.
+ No significant changes are expected

Fixes slave timeout default values

---

CHANGELOG.md
ldfparser/encoding.py
tests/test_encoding.py

- When decoding invalid BCD values the library converts them to the raw value without checking it's validity 
+ Fixes #96 
+ Relevant test cases will be added

Adds additional check when decoding BCD values

---

CHANGELOG.md
codecov.yml
ldfparser/grammar.py
ldfparser/grammars/ldf.lark
ldfparser/parser.py
ldfparser/templates/ldf.jinja2
schemas/ldf.json
tests/ldf/no_signal_subscribers.ldf

- Master and slave declarations (usually at the start of the LDF) are now optional
+ Resolves #95 
+ Existing LDFs are not affected but prototyping LDFs may now be parsed that lack node information

Makes master and slaves declarations optional

---

.github/workflows/build.yml

- Release job had the following error in the latest release, likely due to the command not working under Ubuntu shell.
```
Run echo "::set-output name=current_version::${GITHUB_REF/refs\/tags\/v/}"
echo "::set-output name=current_version::${GITHUB_REF/refs\/tags\/v/}"
shell: sh -e {0}
/__w/_temp/e1bb7b30-00e4-41a0-b76f-c[2](https://github.com/c4deszes/ldfparser/runs/7934175943?check_suite_focus=true#step:7:2)d865da2f[3](https://github.com/c4deszes/ldfparser/runs/7934175943?check_suite_focus=true#step:7:3)9.sh: 1: Bad substitution
Error: Process completed with exit code 2.
```

Fixes release workflow

---

CHANGELOG.md
ldfparser/parser.py
ldfparser/save.py
setup.cfg

- Parser and Save feature now use `os.path.abspath` in order to resolve issues with `pyinstaller` path resolution.
+ Resolves #104 
+ Standard Python installations should not be affected, absolute paths were already resolved there

Enforcing absolute paths when loading grammar

---

CHANGELOG.md
ldfparser/grammar.py
ldfparser/grammars/ldf.lark
ldfparser/parser.py
setup.cfg
tests/ldf/lin13.ldf
tests/test_parser.py

- Diagnostic address section was completely missing from the grammar, this PR resolves that
+ Fixes #107 
+ Snapshot results will deviate due to change in the test LDF files

Adds diagnostic address parsing (LIN 1.3)

---

CHANGELOG.md
ldfparser/parser.py
setup.cfg
setup.py

I fixed a few bugs / "not-so-nice-things" during my first use of your library:
- Removed the tests folder from the python package
- Used everywhere `with open()` where files where opened to avoid opened files
+ Import from own `tests` folder is possible
+ No open files after .ldf parsing
+ Analyze how the change might impact existing code -> there should be no impact
+ Provide evidence that the feature is tested and covered properly -> tested the change with my implementation

Removed tests from py-pkg | no open files after parsing

---

CHANGELOG.md
ldfparser/__init__.py
ldfparser/grammar.py
ldfparser/grammars/ldf.lark
ldfparser/ldf.py
ldfparser/lin.py
ldfparser/node.py
ldfparser/parser.py
ldfparser/templates/ldf.jinja2
tests/ldf/iso17987.ldf
tests/test_lin.py
tests/test_parser.py

- Grammar supports file revision, endianness and ISO versions.
- Version is read into the LDF object
+ Resolves #111 
+ Protocol and language version can now return different types, but it's going to be evident when users have to account for this

ISO17987 support

---

CHANGELOG.md
ldfparser/frame.py
ldfparser/ldf.py
setup.cfg

- `LinUnconditionalFrame::decode` no longer calls the deprecated `parse_raw` function
- `LDF::get_frame` can now return diagnostic frames
+ Deprecated function already called the correct one
+ Users of the `get_frame` function already had to account for the possibility of it returning different types

Returning diag. frames and removing deprecated func. call

---

.flake8
CHANGELOG.md
ldfparser/grammar.py
ldfparser/grammars/ldf.lark
ldfparser/ldf.py
ldfparser/lin.py
ldfparser/node.py
ldfparser/parser.py
ldfparser/templates/ldf.jinja2
schemas/ldf.json
setup.cfg
tests/ldf/j2602_1.ldf
tests/ldf/j2602_1_no_values.ldf
tests/test_lin.py
tests/test_parser.py

- Allow parsing of files with protocol version J2602_1_1.0, which is for J2602:2012 and earlier SAE J2602 protocols. 
- Add new attributes to the master frame and node attributes: `max_header_length` and `response_tolerance`
Note support for J2602_1_2.0(SAE J2602:2021) is not added due to the following reasons:
1.  J2602_1_2.0 renames the term “master” to “commander” and the term “slave” with “responder”, which may require bigger changes.
2. The project I'm working on uses the legacy version, and I don't have example LDF files for the new version.
+  (https://github.com/c4deszes/ldfparser/issues/118)
+ Added new attribute `response_tolenrace` to `LinSlave` class, and default to `None` if loaded from files that are not based on `SAE J2602` protocols.
+ Added new attributes …

Add support for protocol version J2602_1_1.0

---

ldfparser/node.py

Both `supplier_id` and `function_id` have 2 bytes.

update `LinProductId`'s string format

---

.github/workflows/build.yml

- Updated and added CODECOV token to the workflow, disabling CI failure conditions for now
- Updating action versions to latest (node16 deprecation)
- Added stable Python versions to test the library with (3.10, 3.11, 3.12)
+ Release workflow is only impacted by the checkout version update which should be fine, the rest is checked under the PR.

Updating build workflow

---

CHANGELOG.md
ldfparser/grammars/ldf.lark
setup.cfg
tests/ldf/lin_encoders.ldf

add support for upper case E in scientific notation values.
Resolves #134 
+ Analyze how the change might impact existing code
Tests added to pytest validate it's backward compatible. 
+ Provide evidence that the feature is tested and covered properly
I made this new change to the local venv in my system.

Support both upper and lower case E in scientific notation

---

CHANGELOG.md
ldfparser/frame.py
setup.cfg

- The current error when signals overlap doesn't include much information on which signals overlap and in which frame
- The new version includes the frame name and the signals which overlap
+ Resolves #136 
+ Only tested manually and through regression

Improving signal overlapping error message

---

CHANGELOG.md
ldfparser/parser.py
ldfparser/signal.py

- According to the standard a signal can be in multiple frames as long as it's published by the same node
- With this change we allow this mapping, however at the moment it's not checked whether the publishers are the same
#141 
+ For compatibility reasons the existing `signal.frame` is kept but it's only set when one frame is associated with a signal

Multiple frames can be associated with one signal

---

CHANGELOG.md
ldfparser/grammars/ldf.lark
setup.cfg

- Grammar has been updated to allow empty encoders
+ Fixes #138 
+ Tested manually

Allowing empty signal encoders

---

CHANGELOG.md
ldfparser/encoding.py

- Previously the physical values used `int(x)` to round the values, which rounds down
- The new one should be more consistent across input ranges
(Issue filed externally)
+ This change might break user code where users have not fully made sure to limit the input and output ranges, for example a signal intended to be encoded into `0-254` range if the user input could be as high `254.8` then this could lead to an error of the signal overflowing into `255`. But at least the encoder will catch cases if that would go outside it's range

Physical value encoder rounding
